import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";

import { Providers } from "@/components/customized/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter( {
  subsets: [ "latin" ],
  variable: "--font-sans", // ← importante!
} );

const geistMono = Geist_Mono( {
  subsets: [ "latin" ],
  variable: "--font-geist-mono",
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en">
      <body className={`${ inter.variable } ${ geistMono.variable } antialiased`}>
        <Providers>
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
